console.log('tumorBoard.js :-)')


tumorBoard=function(){
    // ini code here
    tumorBoard.loadGPScvs();
};

tumorBoard.parseGPScvs=function(txt){
    //var y = jmat.text2object(txt.result,',');
    return jmat.text2table(txt.result.replace(/,/g,'\t'))
};

tumorBoard.parseGPScvsHTML=function(txt){
    var html = jmat.table2html(tumorBoard.parseGPScvs(txt));
    var tb = jmat.gId('GPScvsTable');
    if(!tb){
        tb = jmat.cEl('table','GPScvsTable');
        jmat.gId('divGPScvs').appendChild(tb);
        tb.classList.add('table','table-striped');
        tb.style.fontSize="small";
    };
    tb.innerHTML=html;
    
    lala = tb;
};

tumorBoard.loadGPScvs=function(){ // load .csv file produced by gps.wustl.edu
    var div0 = document.getElementById('tumorBoard'); // could be null, don't worry
    if(!div0){var div0 = jmat.div()}
    var div1=jmat.cEl('div','divGPScvs');
    div0.appendChild(div1);
    jmat.inputFileTxt(this.parseGPScvsHTML,div1,'<span style="color:blue">Upload .cvs file generated by gps.wustl.edu</span>','accept=".csv"');
};

